name: jdl
recipe: pantheon
config:
  framework: drupal8
  site: jdl8
  id: bb918add-0cd5-47e0-beae-840ede5aeba4
  xdebug: false
  index: false
  edge: true
  cache: false
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_URI: http://jdl.lndo.site
    run:
      - composer global require hirak/prestissimo
      - composer install
  node:
    type: node:12
    run:
      - cd /app/web/themes/custom/jd2 && npm install --prefix=/app/web/themes/custom/jd2
      - npm install --global gulp-cli
#      - cd /app/web/themes/custom/jd2 && gulp
tooling:
  gulp:
    service: node
  node:
    service: node
  npm:
    service: node
excludes:
  - vendor
  - web/core
  - web/libraries
  - web/themes/custom/jd2/node_modules
